- R/future.r
- R/utilities.r
- future.vpaでdet.run=FALSEがちゃんと動くように設定しなおし（det.run=TRUEの場合，1回目のシミュレーションは決定論的シミュレーションだが，det.fun=FALSEの場合には1回目も確率的シミュレーションになるようにした）
- plot_futuresとplot_yieldsで future_replicate (表示するシミュレーションの番号を入れるとそのシミュレーションを選ぶ）を追加
> change future.vpa and utilities

- R/future.r
get.stat3でrec.meanなども見れるようにしました
> get.stat3で加入量もトレースできるように

- DESCRIPTION
- R/rvpa.r
- R/use_rvpa_tmb.r
- inst/executable/rvpa_tmb.cpp
- man/vpa.Rd
- rvpa関数でTMB=TRUEでb.est, b.fix, use.index等を使用したときのbugを修正
- library(TMB)をやめてDESCRIPTIONのSuggestsに移動
> bug fix in rvpa()

- R/future.r
- est.MSY内で不要な将来予測結果が一時保存されていたが、必要ない結果はすぐに削除するように変更。これによって、大量の計算をしたときにメモリが足りなくなる問題が解決されるか？
> delete large-sized object in est.MSY

- R/stock_recruit.r
fit.SRでoptimを繰り返して収束が甘くならないようにしました
> fix fit.SR

- .Rbuildignore
- .travis.yml
- DESCRIPTION
- R/utilities.r
- README.md
- vignettes/SRR-guidline.Rmd
`.travis.yml` を市野川さんのアカウント情報に書き換えていただく必要があります
> :construction: Travisで継続化

- R/rvpa.r
- R/utilities.r
- inst/executable/rvpa_tmb.cpp
- man/get.SRdata.Rd
- man/plot_kobe_gg.Rd
rvpa_tmbでmin.ageとmax.ageが異なる場合（1歳魚と2歳魚の合計個体数などがチューニングの対象となる場合）に対応しました
> Fix rvpa_tmb and Add plot.year option in plot_kobe_gg

- R/stock_recruit.r
- R/utilities.r
- man/SRregime_plot.Rd
- man/fit.SRregime.Rd
fit.SRregimeでfit.SRを使って初期値を決めたり（計算時間短縮のため）、SRregime_plotを修正したりしました
> minor change

- R/stock_recruit.r
L1かつout.AR=FALSEのときのar関数の設定をout.AR=TRUEと同様に (demean = FALSE, method="mle"）
> fix L1 & out.AR=FALSE option

- README.md
Travisのリンク修正しました。
リンク先に飛べればokなので、確認後、勝手にマージしてしまいます
> :construction_worker: Update travis URL

- .travis.yml
"already exists" error occurred on https://travis-ci.com/ichimomo/frasyr/builds/138514819
> :green_heart: Fix git tag error

- R/utilities.r
MSY推定結果を比較（Bmsyなどの管理基準値と漁獲量曲線）するための関数です
> add compare_MSY

- R/stock_recruit.r
> fit.SRregimeのレジーム名をregime.keyと一致するように修正

- R/stock_recruit.r
> fix bug #192

- R/stock_recruit.r
- man/compare_eq_stat.Rd
- man/fit.SR.Rd
> small fix of fit.SRregime

- R/utilities.r
compare_future_performanceの関数の帰り値の3番目に，プロットしたデータを全部返すように変更
> add data in compare_future_performance

- tests/testthat/test-stock-retruit-part.R
丸めはRIだけ一桁緩めてます。6.2e-05のズレを確認してます。
> Add 既知パラメータの推定確認(RIはround(3))

- tests/testthat/test-stock-retruit-part.R
（fshin3さんの https://github.com/fshin3/frasyr/tree/issue282 を修復されたdevにリベースしただけです。）
@fshin3 この更新に関してなにか追加情報がありましたら、コメント編集よろしくお願いします:bow:
> :white_check_mark: Add tests for stock-recruit

- R/rvpa.r
- tests/testthat/test-data.handler.R
sigma.constに値が指定されたときは，sigma.constraintで値を指定しなおしてくださいという警告を出し，プログラムがそこで停止するようにしました．
> give warning when sigma.const is used

- R/diagnostics_vpa.R
- R/rvpa.r
- vignettes/Diagnostics-for-VPA.Rmd
モデル診断スクリプトのブートストラップ法、およびじったー解析のイタレーション数を減らしました。
じったー解析の作図結果のx軸名をinitial value of F of age Maxにしました
> モデル診断スクリプトのイタレーション数減らす

- R/diagnostics_vpa.R
- R/graphics.r
- R/rvpa.r
safe_call(, force = T)関数への変更
変更対象箇所
- R/diagnostics_vpa.R
- R/rvpa.r
- retro.est関数
- boo.vpa関数
> safe_call関数への変更 #383

- R/graphics.r
geom_pointを追加して、plot_vpaで複数シナリオ作図した際に、ltyの他にshapeも変わるようにしました
> plot_vpaにshapeの追加 #385

- R/diagnostics_vpa.R
- R/graphics.r
- vignettes/Diagnostics-for-VPA.Rmd
plot_vpa関数中にplot_year引数を追加することで、plot_vpa関数を使っている
- do_sensitivity_vpa
- do_retrospective_vpa
- do_jackknife_vpa
の3関数でplot_yearを指定できるようになりました
> plot_vpa関数にplot_year引数の追加

- R/graphics.r
%SPR の時系列プロットを詳細版様式に合わせました
Resolve #401
> :lipstick: Modify plot_sprypr()

- R/stock_recruit.r
> add legend on jackknifeSR plot

- vignettes/Diagnostics-for-VPA.Rmd
#418 
2段階法のレトロスペクティブ解析のコード例をvignettesに追加。
> 2段階法のレトロコードをvignettesに追加

- R/tables.R
- tests/testthat/test-tables.R
https://github.com/ichimomo/frasyr_tool/issues/220 でご報告いただいた表の値を修正しました
Resolve #429
> :bug: Correct table values

- R/diagnostics_vpa.R
- R/graphics.r
- vignettes/Diagnostics-for-VPA.Rmd
scale_valueという引数を
- 感度分析
- レトロスペクティブ解析
- ジャックナイフ法
の3関数に追加
https://github.com/ichimomo/frasyr/issues/438#issue-667469050
> 6種類以上のplot_vpa作図問題
